message_post:
  url: /message/post.json
  class: sfRequestRoute
  param: { module: message, action: post, sf_format: json }
  requirements: { sf_method: post }

message_chain:
  url: /message/chain.json
  class: sfRequestRoute
  param: { module: message, action: chain, sf_format: json }
  requirements: { sf_method: post }

recent_message_list:
  url:   /message/recentList.json
  class: sfRequestRoute
  param: { module: message, action: recentList, sf_format: json }
  requirements: { sf_method: post }

message_no_default:
  url:   /message/*
  param: { module: default, action: error }
